apiVersion: apps/v1
kind: Deployment
metadata:
  name: rachnatech-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rachnatech-web
  template:
    metadata:
      labels:
        app: rachnatech-web
    spec:
      containers:
      - name: rachnatech-web
        image: shouryahere/rt:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: rachnatech-db
        - name: DB_PORT
          value: "3306"
        # Add other environment variables as needed
---
apiVersion: v1
kind: Service
metadata:
  name: rachnatech-web
spec:
  type: NodePort
  selector:
    app: rachnatech-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rachnatech-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rachnatech-db
  template:
    metadata:
      labels:
        app: rachnatech-db
    spec:
      containers:
      - name: rachnatech-db
        image: mysql:8.0
        env:
        - name: MYSQL_DATABASE
          value: rachnatech
        - name: MYSQL_USER
          value: rt_admin
        - name: MYSQL_PASSWORD
          value: rt_admin_pass
        - name: MYSQL_ROOT_PASSWORD
          value: rt_root_pass
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: rachnatech-db
spec:
  selector:
    app: rachnatech-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
