apiVersion: apps/v1
kind: Deployment
metadata:
  name: rachnatech-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rachnatech-web
  template:
    metadata:
      labels:
        app: rachnatech-web
    spec:
      containers:
      - name: rachnatech-web
        image: rt:v2
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: rachnatech-web
spec:
  type: NodePort
  selector:
    app: rachnatech-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
